spring:
  application:
    name: "cake-factory"
  datasource:
    url: "jdbc:postgresql://localhost:5431/cakefactory"
    platform: "postgresql"
    password: "password"
    username: "clayton"
    driver-class-name: "org.postgresql.Driver"
  jpa:
#    generate-ddl: "false"
    open-in-view: true
    hibernate:
      ddl-auto: "validate"
#    properties:
#      hibernate:
#        globally_quoted_identifiers: "true"
  flyway:
    url: "jdbc:postgresql://localhost:5431/cakefactory"
    schemas: cakefactory
    user: clayton
    password: password
    enabled: true
    createSchemas: true
#  jackson:
#    serialization:
#      fail-on-empty-bean: "false"

server:
  port: "8080"
  servlet:
    context-path: "/"

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: INFO
  file: logs/cake-factory.log